import type { Metadata } from "next";
import { BookingRequestForm } from "@/components/booking-request-form";
import { CtaButtons } from "@/components/cta-buttons";
import { MobileStickyActions } from "@/components/mobile-sticky-actions";
import { SectionHeading } from "@/components/section-heading";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { getLocale } from "@/lib/i18n";
import { siteConfig } from "@/lib/site-config";

type SearchParams = Promise<{ lang?: string }>;
const copy = { vi: { eyebrow: "Li\u00ean h\u1ec7", heading: "Ch\u1ecdn k\u00eanh li\u00ean h\u1ec7 ph\u00f9 h\u1ee3p", subtext: "G\u1ecdi, nh\u1eafn Zalo ho\u1eb7c \u0111i\u1ec1n form \u0111\u1ec3 K2 ph\u1ea3n h\u1ed3i s\u1edbm.", infoTitle: "Th\u00f4ng tin li\u00ean h\u1ec7", phone: "\u0110i\u1ec7n tho\u1ea1i", zalo: "Zalo", address: "\u0110\u1ecba ch\u1ec9", zaloText: "Ph\u00f9 h\u1ee3p khi b\u1ea1n mu\u1ed1n h\u1ecfi ph\u00f2ng nhanh tr\u01b0\u1edbc khi \u0111\u1eb7t.", quickTitle: "Khi n\u00e0o n\u00ean g\u1ecdi ngay", quickItems: ["Khi c\u1ea7n h\u1ecfi ph\u00f2ng c\u00f2n tr\u1ed1ng trong ng\u00e0y.", "Khi \u0111i theo nh\u00f3m nh\u1ecf ho\u1eb7c gia \u0111\u00ecnh v\u00e0 mu\u1ed1n ch\u1ecdn nhanh lo\u1ea1i ph\u00f2ng ph\u00f9 h\u1ee3p.", "Khi c\u1ea7n trao \u0111\u1ed5i th\u00eam v\u1ec1 gi\u1edd \u0111\u1ebfn ho\u1eb7c nhu c\u1ea7u \u0111\u1eb7c bi\u1ec7t."] }, en: { eyebrow: "Contact", heading: "Choose the easiest contact channel", subtext: "Call, message on Zalo or send the form for a quick reply from K2.", infoTitle: "Contact details", phone: "Phone", zalo: "Zalo", address: "Address", zaloText: "Best when you want a quick room check before booking.", quickTitle: "When to call directly", quickItems: ["When you need a room check for today.", "When you travel with family or a small group and want the right room fast.", "When you need to confirm arrival time or a special request."] } } as const;
export const metadata: Metadata = { title: "Li\u00ean h\u1ec7", description: "Li\u00ean h\u1ec7 K2 Homestay qua \u0111i\u1ec7n tho\u1ea1i, Zalo ho\u1eb7c form \u0111\u1eb7t ph\u00f2ng." };
export default async function ContactPage({ searchParams }: { searchParams?: SearchParams }) { const locale = getLocale((await searchParams)?.lang); const text = copy[locale]; return <div className="min-h-screen bg-[var(--bg-page)] text-[var(--ink-strong)]"><SiteHeader locale={locale} currentPath="/contact" /><main className="px-4 pb-24 pt-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><section className="rounded-[36px] border border-[var(--line)] bg-[var(--hero-surface)] p-6 shadow-[0_24px_80px_rgba(37,26,16,0.08)] sm:p-8"><SectionHeading eyebrow={text.eyebrow} title={text.heading} description={text.subtext} /><div className="mt-6"><CtaButtons locale={locale} /></div></section><section className="mt-8 grid gap-6 lg:grid-cols-[0.95fr_1.05fr]"><div className="grid gap-6"><section className="rounded-[32px] border border-[var(--line)] bg-[var(--surface)] p-6 shadow-sm"><h2 className="font-display text-4xl">{text.infoTitle}</h2><div className="mt-5 grid gap-3 text-sm text-[var(--ink-muted)]"><div className="rounded-[24px] bg-[var(--card-soft)] p-5"><div className="font-semibold text-[var(--ink-strong)]">{text.phone}</div><div className="mt-1">{siteConfig.phoneDisplay}</div></div><div className="rounded-[24px] bg-[var(--card-soft)] p-5"><div className="font-semibold text-[var(--ink-strong)]">{text.zalo}</div><div className="mt-1">{text.zaloText}</div></div><div className="rounded-[24px] bg-[var(--card-soft)] p-5"><div className="font-semibold text-[var(--ink-strong)]">{text.address}</div><div className="mt-1">{locale === "en" ? siteConfig.addressEn : siteConfig.address}</div></div></div></section><section className="rounded-[32px] border border-[var(--line)] bg-[var(--surface)] p-6 shadow-sm"><h2 className="font-display text-4xl">{text.quickTitle}</h2><ul className="mt-5 grid gap-3 text-sm leading-7 text-[var(--ink-muted)]">{text.quickItems.map((item) => (<li key={item} className="list-disc pl-5 marker:text-[var(--ink-soft)]">{item}</li>))}</ul></section></div><div id="booking-form"><BookingRequestForm sourcePage="contact" locale={locale} /></div></section></div></main><SiteFooter locale={locale} /><MobileStickyActions locale={locale} /></div>; }