import type { Metadata } from "next";
import { BookingRequestForm } from "@/components/booking-request-form";
import { CtaButtons } from "@/components/cta-buttons";
import { MobileStickyActions } from "@/components/mobile-sticky-actions";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { getLocale, uiCopy } from "@/lib/i18n";

type SearchParams = Promise<{ room?: string; lang?: string }>;
export const metadata: Metadata = { title: "\u0110\u1eb7t ph\u00f2ng", description: "G\u1eedi y\u00eau c\u1ea7u \u0111\u1eb7t ph\u00f2ng tr\u1ef1c ti\u1ebfp cho K2 Homestay qua form, \u0111i\u1ec7n tho\u1ea1i ho\u1eb7c Zalo." };
export default async function BookingPage({ searchParams }: { searchParams: SearchParams }) { const params = await searchParams; const locale = getLocale(params.lang); const copy = uiCopy[locale]; const pageCopy = { vi: { eyebrow: "\u0110\u1eb7t ph\u00f2ng tr\u1ef1c ti\u1ebfp", heading: "Ch\u1ecdn ng\u00e0y \u1edf v\u00e0 g\u1eedi form nhanh", subtext: "G\u1ecdi, nh\u1eafn Zalo ho\u1eb7c \u0111i\u1ec1n form \u0111\u1ec3 K2 ph\u1ea3n h\u1ed3i s\u1edbm.", why: "V\u00ec sao n\u00ean \u0111\u1eb7t tr\u1ef1c ti\u1ebfp", bullets: ["Bi\u1ebft nhanh ph\u00f2ng c\u00f2n tr\u1ed1ng.", "D\u1ec5 trao \u0111\u1ed5i \u0111\u00fang s\u1ed1 kh\u00e1ch v\u00e0 nhu c\u1ea7u.", "G\u1ecdi ho\u1eb7c Zalo \u0111\u1ec3 x\u00e1c nh\u1eadn nhanh."] }, en: { eyebrow: "Direct booking", heading: "Pick your dates and send the form quickly", subtext: "Call, message on Zalo or send the form for a quick reply from K2.", why: "Why book direct", bullets: ["Check room availability faster.", "Share your guest count and needs clearly.", "Call or use Zalo for a quick confirmation."] } } as const; const text = pageCopy[locale]; return <div className="min-h-screen bg-[var(--bg-page)] text-[var(--ink-strong)]"><SiteHeader locale={locale} currentPath="/booking" /><main className="px-4 pb-24 pt-2 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-4 sm:space-y-5"><section className="rounded-[24px] border border-[var(--line)] bg-[var(--hero-surface)] p-4 shadow-[0_18px_50px_rgba(37,26,16,0.08)] sm:p-5"><div className="grid gap-3 lg:grid-cols-[0.88fr_1.12fr] lg:items-start lg:gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[var(--ink-soft)]">{text.eyebrow}</p><h1 className="mt-1 font-display text-xl sm:text-3xl">{text.heading}</h1><p className="mt-2 text-sm leading-5 text-[var(--ink-muted)] sm:leading-6">{text.subtext}</p><div className="mt-3"><CtaButtons locale={locale} /></div></div><BookingRequestForm sourcePage="booking" defaultRoomSlug={params.room} locale={locale} commitmentText={copy.bookingForm.compactCommitment} /></div></section><section className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-4 shadow-sm sm:p-5"><h2 className="font-display text-lg sm:text-2xl">{text.why}</h2><ul className="mt-3 grid gap-2 text-sm leading-5 text-[var(--ink-muted)] md:grid-cols-3">{text.bullets.map((item) => (<li key={item} className="rounded-[16px] bg-[var(--card-soft)] px-3.5 py-2.5">{item}</li>))}</ul></section></div></main><SiteFooter locale={locale} /><MobileStickyActions locale={locale} /></div>; }